"""Azure: a spot-capable GPU VM from generated Bicep, cloud-init runs the job, an auto-shutdown schedule caps the bill."""

from __future__ import annotations

import base64
import subprocess
from pathlib import Path

from protea.training.remote.base import JobPlan, PlanRequest, RemoteAdapter
from protea.training.remote.ssh import JOB_SCRIPT

BICEP = """// Generated by `protea train remote` — review before deploying.
param location string = '{location}'
param vmName string = '{vm_name}'
param adminUser string = '{admin_user}'
@secure()
param sshPublicKey string
@secure()
param customData string
param shutdownTime string = '{shutdown_utc}'

resource vnet 'Microsoft.Network/virtualNetworks@2023-09-01' = {{
  name: '${{vmName}}-vnet'
  location: location
  properties: {{
    addressSpace: {{ addressPrefixes: [ '10.10.0.0/24' ] }}
    subnets: [ {{ name: 'default', properties: {{ addressPrefix: '10.10.0.0/24' }} }} ]
  }}
}}
resource pip 'Microsoft.Network/publicIPAddresses@2023-09-01' = {{
  name: '${{vmName}}-pip'
  location: location
  sku: {{ name: 'Standard' }}
  properties: {{ publicIPAllocationMethod: 'Static' }}
}}
resource nic 'Microsoft.Network/networkInterfaces@2023-09-01' = {{
  name: '${{vmName}}-nic'
  location: location
  properties: {{
    ipConfigurations: [ {{
      name: 'ipconfig1'
      properties: {{ subnet: {{ id: vnet.properties.subnets[0].id }}, publicIPAddress: {{ id: pip.id }} }}
    }} ]
  }}
}}
resource vm 'Microsoft.Compute/virtualMachines@2024-03-01' = {{
  name: vmName
  location: location
  properties: {{
    hardwareProfile: {{ vmSize: '{vm_size}' }}
    priority: '{priority}'
    {eviction}
    storageProfile: {{
      imageReference: {{ publisher: 'canonical', offer: 'ubuntu-24_04-lts', sku: 'server', version: 'latest' }}
      osDisk: {{ createOption: 'FromImage', diskSizeGB: 256, managedDisk: {{ storageAccountType: 'Premium_LRS' }} }}
    }}
    osProfile: {{
      computerName: vmName
      adminUsername: adminUser
      customData: customData
      linuxConfiguration: {{
        disablePasswordAuthentication: true
        ssh: {{ publicKeys: [ {{ path: '/home/${{adminUser}}/.ssh/authorized_keys', keyData: sshPublicKey }} ] }}
      }}
    }}
    networkProfile: {{ networkInterfaces: [ {{ id: nic.id }} ] }}
  }}
}}
// Hard stop regardless of what the job does: DevTestLab auto-shutdown at the runtime limit.
resource shutdown 'Microsoft.DevTestLab/schedules@2018-09-15' = {{
  name: 'shutdown-computevm-${{vmName}}'
  location: location
  properties: {{
    status: 'Enabled'
    taskType: 'ComputeVmShutdownTask'
    dailyRecurrence: {{ time: shutdownTime }}
    timeZoneId: 'UTC'
    targetResourceId: vm.id
    notificationSettings: {{ status: 'Disabled' }}
  }}
}}
output publicIp string = pip.properties.ipAddress
"""

CLOUD_INIT = """#cloud-config
package_update: true
packages: [python3-venv, git]
write_files:
  - path: /opt/protea-job.sh
    permissions: '0755'
    encoding: b64
    content: {job_b64}
runcmd:
  - [ bash, -lc, "curl -fsSL https://raw.githubusercontent.com/Azure/azhpc-images/master/ubuntu/common/install_nvidiagpudriver.sh | bash || true" ]
  - [ bash, -lc, "git clone https://github.com/MalcolmGov/protea /opt/protea" ]
  - [ bash, -lc, "cd /opt/protea && nohup /opt/protea-job.sh > /var/log/protea-job.log 2>&1 &" ]
"""


class AzureAdapter(RemoteAdapter):
    name = "azure"

    def plan(self, req: PlanRequest) -> JobPlan:
        cfg, run_id = req.cfg, req.run_id
        az = self.remote.azure
        assert az is not None
        plan = self._base_plan(
            req,
            safeguards=[
                "DevTestLab auto-shutdown schedule deallocates the VM at the runtime limit even if the job hangs"
            ],
        )
        job = JOB_SCRIPT.format(
            workdir="/opt/protea",
            run_id=run_id,
            storage=self.remote.storage.uri,
            max_minutes=plan.max_runtime_minutes,
            idle_minutes=plan.idle_shutdown_minutes,
            sync_minutes=self.remote.checkpoint_sync_minutes,
            command=plan.command,
            shutdown="true",
        )
        cloud_init = CLOUD_INIT.format(job_b64=base64.b64encode(job.encode()).decode())
        vm_name = f"protea-{cfg.output.experiment_name}"[:60].replace("_", "-")
        shutdown_minutes = plan.max_runtime_minutes + 30
        # placeholder default; deploy.sh passes the real wall-clock shutdown time computed at deploy time
        shutdown_utc = f"{(shutdown_minutes // 60) % 24:02d}{shutdown_minutes % 60:02d}"
        bicep = BICEP.format(
            location=az.location,
            vm_name=vm_name,
            admin_user=az.admin_user,
            vm_size=az.vm_size,
            priority="Spot" if self.remote.spot else "Regular",
            eviction="evictionPolicy: 'Deallocate'" if self.remote.spot else "",
            shutdown_utc=shutdown_utc,
        )
        deploy = (
            "#!/usr/bin/env bash\nset -euo pipefail\n"
            f"RG={az.resource_group}\nSHUTDOWN=$(date -u -d '+{shutdown_minutes} minutes' +%H%M)\n"
            f'az group create -n "$RG" -l {az.location}\n'
            f'az deployment group create -g "$RG" -f main.bicep '
            f'-p sshPublicKey="$(cat {az.ssh_public_key_path})" -p customData="$(base64 -w0 cloud-init.yaml)" '
            '-p shutdownTime="$SHUTDOWN"\n'
        )
        plan.artifacts = {"main.bicep": bicep, "cloud-init.yaml": cloud_init, "job.sh": job, "deploy.sh": deploy}
        return plan

    def launch(self, plan: JobPlan, artefact_dir: Path) -> str:
        subprocess.run(["bash", str(artefact_dir / "deploy.sh")], check=True, cwd=artefact_dir)
        az = self.remote.azure
        assert az is not None
        return f"azure:{az.resource_group}"
