"""Generic SSH host (any rented box with a GPU): a bash job script with runtime limit, checkpoint sync and shutdown."""

from __future__ import annotations

import shlex
import subprocess
from pathlib import Path

from protea.training.remote.base import JobPlan, PlanRequest, RemoteAdapter

JOB_SCRIPT = """#!/usr/bin/env bash
# Generated by `protea train remote` — review before running. Secrets come from the environment by name.
set -euo pipefail
WORKDIR={workdir}
RUN_ID={run_id}
STORAGE={storage}
MAX_MINUTES={max_minutes}
IDLE_MINUTES={idle_minutes}
SYNC_MINUTES={sync_minutes}
: "${{HF_TOKEN:?HF_TOKEN must be set in the environment}}"

mkdir -p "$WORKDIR" && cd "$WORKDIR"
if [ ! -d .venv ]; then python3 -m venv .venv; fi
. .venv/bin/activate
pip install -q -e ".[train]"

# dataset and previous checkpoints come from external storage; the instance disk is disposable
protea-storage pull "$STORAGE" "$WORKDIR/protea_data" "$WORKDIR/runs" || true

sync_loop() {{ while sleep "$((SYNC_MINUTES * 60))"; do protea-storage push "$WORKDIR/runs" "$STORAGE" || true; done; }}
sync_loop & SYNC_PID=$!

checkpoint_and_exit() {{
  echo "SIGTERM: syncing checkpoints"; kill "$SYNC_PID" || true
  protea-storage push "$WORKDIR/runs" "$STORAGE" || true
  exit 143
}}
trap checkpoint_and_exit TERM INT

set +e
timeout --signal=TERM --kill-after=120 "$((MAX_MINUTES * 60))" {command}
STATUS=$?
set -e
kill "$SYNC_PID" || true
protea-storage push "$WORKDIR/runs" "$STORAGE"

# idle shutdown: nothing else to do on this box once the run has finished or died
if [ "{shutdown}" = "true" ]; then sleep "$((IDLE_MINUTES * 60))" && sudo shutdown -h now; fi
exit $STATUS
"""


class SshAdapter(RemoteAdapter):
    name = "ssh"

    def plan(self, req: PlanRequest) -> JobPlan:
        cfg, run_id = req.cfg, req.run_id
        ssh = self.remote.ssh
        assert ssh is not None
        max_minutes = self.remote.max_runtime_minutes or cfg.budget.max_runtime_minutes
        idle = self.remote.idle_shutdown_minutes or cfg.budget.idle_shutdown_minutes
        plan = self._base_plan(
            req,
            safeguards=[f"`timeout` wraps the trainer; `shutdown -h` after {idle} idle minutes"],
        )
        script = JOB_SCRIPT.format(
            workdir=shlex.quote(ssh.workdir),
            run_id=shlex.quote(run_id),
            storage=shlex.quote(self.remote.storage.uri),
            max_minutes=max_minutes,
            idle_minutes=idle,
            sync_minutes=self.remote.checkpoint_sync_minutes,
            command=plan.command,
            shutdown="true" if ssh.shutdown_when_done else "false",
        )
        target = f"{ssh.user}@{ssh.host}"
        plan.artifacts = {
            "job.sh": script,
            "launch.sh": (
                "#!/usr/bin/env bash\nset -euo pipefail\n"
                f"scp -P {ssh.port} job.sh {target}:/tmp/protea-job.sh\n"
                f"ssh -p {ssh.port} {target} 'chmod +x /tmp/protea-job.sh && "
                'nohup env HF_TOKEN="$HF_TOKEN" /tmp/protea-job.sh > /tmp/protea-job.log 2>&1 &\'\n'
            ),
        }
        return plan

    def launch(self, plan: JobPlan, artefact_dir: Path) -> str:
        ssh = self.remote.ssh
        assert ssh is not None
        key = ["-i", ssh.key_path] if ssh.key_path else []
        target = f"{ssh.user}@{ssh.host}"
        subprocess.run(
            ["scp", "-P", str(ssh.port), *key, str(artefact_dir / "job.sh"), f"{target}:/tmp/protea-job.sh"], check=True
        )
        subprocess.run(
            [
                "ssh",
                "-p",
                str(ssh.port),
                *key,
                target,
                "chmod +x /tmp/protea-job.sh && nohup /tmp/protea-job.sh > /tmp/protea-job.log 2>&1 &",
            ],
            check=True,
        )
        return f"ssh:{target}:/tmp/protea-job.log"
